### ISSUE TITLE
这个carto的windows版本的建图测试

### ISSUE THREAD

**Issue by lawrence2q** [tpengti/cartographer_windows#1]
作者真厉害，整个给移植到windows了。
但，本人带了几组2D激光雷达数据进去建图测试，感觉没有优化效果。你是不是没有将scanmach的部分跑起来。
我图片传不上来。

**Comment by tpengti** [comment]
@lawrence2q 
你好，那代码只提供了模块的测试接口，如果要整个运行，GlobalTrajectoryBuilder::AddRangefinderData开始传入相关数据即可(可以参考ROS的数据调用方式)

**Comment by ZhiyuLiu1993** [comment]
@tpengti 作者，你好，我交叉编译了一个在arm上跑的cartographer，目前已经可以运行了，但是目前还不知道如何将构建的地图和轨迹绘制，想问下你在windows上不用ros如何看地图和轨迹的？
